In [1]:
5+5

10

In [2]:
print("This is good")


This is good


In [3]:
5+5


10

In [6]:
str1="I Like apples , mangoes , bananas , pineapple"
str1.split('a')

['I Like ', 'pples , m', 'ngoes , b', 'n', 'n', 's , pine', 'pple']

In [5]:
str1.find('man')

16

In [7]:
tup1 = (1,'a',True,3.14,5+7j)
tup1

(1, 'a', True, 3.14, (5+7j))

In [8]:
type(tup1)

tuple

In [12]:
tup1[0]

tup1[0:4]

(1, 'a', True, 3.14)

In [13]:
tup1[-1]

(5+7j)

In [15]:
tup1[2]="hello"

TypeError: 'tuple' object does not support item assignment

In [16]:
len(tup1)

5

In [17]:
tup2=(23,False,"hello",3.3333,3+9j)
tup1+tup2

(1, 'a', True, 3.14, (5+7j), 23, False, 'hello', 3.3333, (3+9j))

In [18]:
tup1*3+tup2*5

(1,
 'a',
 True,
 3.14,
 (5+7j),
 1,
 'a',
 True,
 3.14,
 (5+7j),
 1,
 'a',
 True,
 3.14,
 (5+7j),
 23,
 False,
 'hello',
 3.3333,
 (3+9j),
 23,
 False,
 'hello',
 3.3333,
 (3+9j),
 23,
 False,
 'hello',
 3.3333,
 (3+9j),
 23,
 False,
 'hello',
 3.3333,
 (3+9j),
 23,
 False,
 'hello',
 3.3333,
 (3+9j))

In [19]:
tup3=(0,2,4,1,7,4,6)
max(tup3)

7

In [20]:
min(tup3)

0

In [21]:
l1=[3,True,'Hi',5+6j]
l1

[3, True, 'Hi', (5+6j)]

In [22]:
l1[0]

3

In [23]:
l1[1:3]

[True, 'Hi']

In [24]:
l1[-2]

'Hi'

In [25]:
l1[0]=100

In [26]:
l1

[100, True, 'Hi', (5+6j)]

In [27]:
l1.append("Spend")

In [28]:
l1

[100, True, 'Hi', (5+6j), 'Spend']

In [30]:
l1.pop()

'Spend'

In [31]:
l1

[100, True, 'Hi', (5+6j)]

In [32]:
l1.reverse()

In [34]:
l1


[(5+6j), 'Hi', True, 100]

In [37]:
l1.insert(1,"jaa")

In [38]:
l1

[(5+6j), 'jaa', 'HI', 'Hi', True, 100]

In [39]:
l2=['guava','apple','banana','mango']

In [40]:
l2.sort()

In [41]:
l2

['apple', 'banana', 'guava', 'mango']

In [42]:
l1+l2

[(5+6j), 'jaa', 'HI', 'Hi', True, 100, 'apple', 'banana', 'guava', 'mango']

In [43]:
l1*2

[(5+6j), 'jaa', 'HI', 'Hi', True, 100, (5+6j), 'jaa', 'HI', 'Hi', True, 100]

In [44]:
d1={'Mango':50,'Apple':40,'Gauva':60,'Banana':30}
d1

{'Mango': 50, 'Apple': 40, 'Gauva': 60, 'Banana': 30}

In [45]:
type(d1)

dict

In [46]:
d1.keys()

dict_keys(['Mango', 'Apple', 'Gauva', 'Banana'])

In [47]:
d1.values()

dict_values([50, 40, 60, 30])

In [48]:
d1['Orange']=70
d1

{'Mango': 50, 'Apple': 40, 'Gauva': 60, 'Banana': 30, 'Orange': 70}

In [52]:
d1['Banana']=45


In [53]:
d1

{'Mango': 50,
 'Apple': 40,
 'Gauva': 60,
 'Banana': 45,
 'Orange': 70,
 'banana': 45}

In [54]:
d1.pop('banana')

45

In [55]:
d1

{'Mango': 50, 'Apple': 40, 'Gauva': 60, 'Banana': 45, 'Orange': 70}

In [58]:
d2={'Strawberry':90,'Grapes':65,'Papaya':50}
d1.update(d2)
d1

{'Mango': 50,
 'Apple': 40,
 'Gauva': 60,
 'Banana': 45,
 'Orange': 70,
 'Strawberry': 90,
 'Grapes': 65,
 'Papaya': 50}

In [61]:
s1={1,3.14,'Spark',True,3.14,1,3.14}
s1

{1, 3.14, 'Spark'}

In [60]:
type(s1)

set

In [62]:
s1.add('Hello')

In [63]:
s1

{1, 3.14, 'Hello', 'Spark'}

In [64]:
s1.add(False)

In [65]:
s1

{1, 3.14, False, 'Hello', 'Spark'}

In [66]:
s1.remove('Hello')

In [67]:
s1

{1, 3.14, False, 'Spark'}

In [70]:
s1.update([10,20.3,53,5+5j])

In [71]:
s1

{(5+5j), 1, 10, 20.3, 3.14, 53, False, 'Spark'}

In [73]:
s2={30,3.2222,"Hello",False}

In [74]:
s1.intersection(s2)

{False}

In [6]:
s1=('a','d','c')
if 'z' in s1:
    print('z is in s1')
else:
    print('z is not in s1')

z is not in s1


In [7]:
def hello():
    print('Hello World')

In [8]:
hello()

Hello World


In [9]:
g=lambda x:x*x*x


In [10]:
g(7)

343

In [14]:
l1=[87,56,90,34,67,98]
final_list=list(filter(lambda x: (x%2!=0),l1))

In [15]:
final_list

[87, 67]

In [16]:
l2=[1,2,3,4,5,6,7,8,9]
new_list=list(map(lambda x: (x*2),l2))

In [17]:
new_list

[2, 4, 6, 8, 10, 12, 14, 16, 18]

In [18]:
from functools import reduce

In [24]:
sum=(reduce(lambda x,y: (x+y),new_list))

In [25]:
sum

90

In [30]:
class Phone:
    def set_color(self,color):
        self.color=color
        
    def set_cost(self,cost):
        self.cost=cost
        
    def show_color(self):
        return self.color
    
    def show_cost(self):
        return self.cost
    
    def make_call(self):
        print("Make call")
        
    def play_games(self):
        print("play games")

In [38]:
p1=Phone()
p1.set_color("blue")
p1.set_cost(50000)

In [40]:
p1.show_color()

'blue'

In [41]:
p1.show_cost()

50000

In [46]:
class Employee:
    def __init__(self,name,age,salary,gender):
        self.name=name
        self.age=age
        self.salary=salary
        self.gender=gender
    
    def employee_details(self):
        print("Name of employee is",self.name)
        print("Age of employee is",self.age)
        print("Salary of employee is",self.salary)
        print("Gender of employee is",self.gender)                

In [47]:
e1=Employee('Sam',32,1500000,'Male')

In [48]:
e1.employee_details()

Name of employee is Sam
Age of employee is 32
Salary of employee is 1500000
Gender of employee is Male


In [73]:
class Vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
        
    def show_details(self):
        print("I am a Vehicle")
        print("Mileage of vehicle is",self.mileage)
        print("Cost of vehicle is",self.cost)

In [74]:
v1=Vehicle(500,7000)
v1.show_details()

I am a Vehicle
Mileage of vehicle is 500
Cost of vehicle is 7000


In [81]:
class Car(Vehicle):
    def __init__(self,mileage,cost,tyres,hp):
        super().__init__(mileage,cost)
        self.tyres=tyres
        self.hp=hp
    
    def show_car(self):
        print("I am a car")
        print("Number of tyres are",self.tyres)
        print("Valu of Horse power is",self.hp)

In [83]:
c1 = Car(200,40000,5,500)
c1.show_car()

I am a car
Number of tyres are 5
Valu of Horse power is 500


In [72]:
c1.show_details()

I am a Vehicle
Mileage of vehicle is 200
Cost of vehicle is 4000


In [68]:
c1.show_car()

I am a car


In [3]:
import numpy as np
n1=np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [4]:
n2=np.array([[10,20,30,40],[40,30,20,10]])
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [5]:
type(n1)

numpy.ndarray

In [6]:
type(n2)

numpy.ndarray

In [7]:
n0=np.zeros((5,5))
n0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
nf=np.full((8,9),100)
nf

array([[100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100, 100, 100, 100, 100]])

In [9]:
nr=np.arange(10,25)
nr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
nrfi=np.arange(10,25,2)
nrfi

array([10, 12, 14, 16, 18, 20, 22, 24])

In [11]:
nrdm=np.random.randint(1,100,10)
nrdm

array([12, 98, 44, 60, 23, 59, 72, 54, 69, 74])

In [15]:
nshp=np.array([[1,2,3,4],[4,5,6,7]])
nshp.shape

(2, 4)

In [16]:
nshp.shape=(4,2)

In [20]:
nshp.shape=(8,1)

In [21]:
nshp

array([[1],
       [2],
       [3],
       [4],
       [4],
       [5],
       [6],
       [7]])

In [23]:
na=np.array([10,20,30])
nb=np.array([40,50,60])
np.vstack((na,nb))

array([[10, 20, 30],
       [40, 50, 60]])

In [24]:
np.hstack((na,nb))

array([10, 20, 30, 40, 50, 60])

In [25]:
np.column_stack((na,nb))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [26]:
nc=np.array([10,20,30,40,50,60,70])
nd=np.array([50,60,70,80,90])

np.intersect1d(nc,nd)

array([50, 60, 70])

In [27]:
np.setdiff1d(nc,nd)

array([10, 20, 30, 40])

In [28]:
np.setdiff1d(nd,nc)

array([80, 90])

In [31]:
ne=np.array([10,20,30])
nf=np.array([40,50,60])

np.sum([ne,nf])

array([50, 70, 90])

In [32]:
np.sum([ne,nf],axis=0)

array([50, 70, 90])

In [33]:
np.sum([ne,nf],axis=1)

array([ 60, 150])

In [34]:
ng=np.array([10,20,30])
ng=ng+10
ng

array([20, 30, 40])

In [35]:
ng=ng-5
ng

array([15, 25, 35])

In [36]:
ng=ng*2
ng

array([30, 50, 70])

In [37]:
ng=ng/10
ng

array([3., 5., 7.])

In [60]:
nh=([10,20,30,55,60,40,70,80])
ni=np.random.randint(1,50,10)
np.mean(nh)
np.mean(ni)

33.5

In [61]:
np.median(nh)

47.5

In [62]:
np.std(nh)

23.10810193417019

In [63]:
np.save('my_numpy',ni)

In [64]:
nj=np.load('my_numpy.npy')

In [65]:
nj

array([48, 10, 31, 32, 36, 41, 41, 39, 15, 42])